server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.47.128
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true



threadPool:
  coreSize: 100
  maxSize: 500
  keepAlive: 60
  blockingSize: 10000