server:
  port: 18081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhsot:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall-pms-tx-group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.47.128:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root


  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.47.128

  rabbitmq:
    host: 192.168.47.128
    username: admin
    password: admin
    virtual-host: /vh
    port: 5672
    publisher-confirm-type: correlated  #同步确认  correlated 异步确认
    publisher-returns: true #确定消息是否到达队列

mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml #读取映射文件
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto #默认使用数据库自增
logging:
  level:
    com.atguigu.gmall: debug
feign:
  sentinel:
    enabled: true


